version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/library"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "npm dependencies"
